### ISSUE TITLE
what are the intended usage for this programming language 

### ISSUE THREAD

**Issue by motazsaad** [cube-projects/cube-lang#1]
Hi Kais, 
Thanks for your efforts, it sounds interesting. 
It would be very nice if you provide information about the intended usage for this programming language. For instance, is it suitable for data analysis? web development? education?, .........? 

How do you call the person who speaks this language :)? For example, the one who speaks python is called Pythonista. Giving such names would draw attention to your language. 

For me, I need to be convinced first with this language and see clearly it is useful for something before becoming a speaker of this language. Your description for the language focuses more on the syntax. Please show some specific code examples that are very easy to do it with cube rather than other programming languages. 

I hope my review is useful and helpful for you. 
Please let me know if you have any question. 
Motaz

**Comment by kaisdukes** [comment]
Hi Motaz,

This is a valuable feedback.

1. Cube is a general-purpose language for for application development and data analysis. On language philosophy, perhaps 'Cubism' for clear, readable code written by 'Cubic' programmers? The language introduction has now been updated to reflect this. 

2. For further code examples, this is a great idea, and we we are setting up the project website which should provide more examples with practical usage. I've set up a separate ticket for this.

Kind Regards,
Kais
